### ISSUE TITLE
General PCB Notes

### ISSUE THREAD

**Issue by kyrel8silva** [Skeeter4life/SuperCapBike-Hardware#1] opened 2024-11-13 04:45 UTC
Hey man! I just gave the schematic and PCB a quick look over. It looks pretty good! I'm impressed with how deep you have driven into the datasheets for a lot of these components. You must have learnt so much designing this board! It's crazy to think of how many little nuanced things get taken into account when designing something like this, especially something that needs to handle a lot of power. I've noted a few things below that may come up in some of your testing. 

I'm not sure the xtal oscillator chosen will operate as intended. Normally for Atmega chips a xtal or ceramic oscillator is set between xtal1 and xtal 2. Buffer capacitors are also required for stability. 
![xtal](https://github.com/user-attachments/assets/07c44764-4f4d-4ae9-a519-819536bbf10c)

H-bridge drivers are only rated for 8V min. This means the drivers will only work for ~0.5 tau of the capacitor bank time constants. 

Possibly need to add snubber or bi-directional TVS diodes to h-bridge outputs. Voltage spike by inductive load may cause damage to the circuit.

Some traces/vias need to be increased in size. Trace width calculators are handy for this sort of calculation.

Ground return paths can cause some interference on the analog measurements. Separation and suppression of the MOSFET's current path could help this. 

Need to add bulk capacitance should be added to the following:
-uln2003 5V to gnd
-H-bridge FET's
-Power Rails
-I2C multiplexer

Just a thought also, use of an Arduino Mega may help simplify some things. The increased analog pins would remove the need for the i2c mux. Also, more flash and ram would be a nice help. Also with the Arduino Mega, it could be modified into a daughter board that plugs into the existing pin headers. 

Let me know if you have any questions or want to go through a review sometime.

**Comment by Fischer-Andrew** [comment] 2024-11-13 22:02
Hello [kyrel8silva](https://github.com/kyrel8silva), thank you very much for the kind comments, and your well-documented insights. Below, I have responded to each inquiry with my reasoning/thought process: 

1) I'm not sure the xtal oscillator chosen will operate as intended. Normally for Atmega chips a xtal or ceramic oscillator is set between xtal1 and xtal 2. Buffer capacitors are also required for stability.

    Totally valid, however, I have opted for a fully contained TTL HCMOS clock oscillator [[1]]. It reduced the total number of components, as I should be able to just put the output of it onto XTAL1. This decreases the clock's susceptibility to noise. I have not been able to verify it is operating at 16MHz, however, ATmega328 datasheet references the need to change the CKSEL Fuses to use the internal 125kHz clock. I have not done this and I am able to run the ADC.  

![image](https://github.com/user-attachments/assets/1d524766-0e8d-44f0-8629-ef4a80912a61)

2) Possibly need to add snubber or bi-directional TVS diodes to h-bridge outputs. Voltage spike by inductive load may cause damage to the circuit.

    Honestly, I had not even heard of what a TVS diode was until you mentioned it (I have not even formally learned about diodes/transistors yet!).  I got pretty excited when I realized I could use that inductive spike in my half-bridge driver there for regenerative braking, and optimistically left the MOSFETs body diodes to do all the work. However, I definitely can see this being a problem, and potentially damaging the capacitors dielectric or generating an excess amount of heat in the motor. After you have mentioned it, a potential fix I am thinking about is adding two TVS diodes. The first TVS diode should have a breakdown voltage of 16V, and the other 32V, both carrying the excess back emf's current to ground. I would use a MOSFET to switch between the two TVS diodes if I am in series or parallel mode. I hope I am understanding the concept here correctly. 

3) Some traces/vias need to be increased in size. Trace width calculators are handy for this sort of calculation.

    Ah, shoot, funnily enough, I did use a trace width calculator for the main traces such as the phases, the UCC37324P (even though I am seriously thinking now it does not need to be that wide), and the 12V fuse. I kept the standard trace widths and via sizes for everything else as they are all just carrying low current signals/serial data. I would definitely like to discuss this further with you. Also, it is worth re-iterating, that the final version of this board will have 2oz copper, not 1oz. 


4) Ground return paths can cause some interference on the analog measurements. Separation and suppression of the MOSFET's current path could help this.

    I definitely can see how MOSFETs can interfere with the ADC on the ATmega. I don't have any real experience in EMI reduction/testing, but I did look into separating analog and digital grounds, if this is what you are referring to. It seems to be quite a controversial topic as some experts have said that it is entirely not worth it. If I recall correctly, one of the main issues with doing that is that you lose more by sacrificing the capacitive effect of having a uniform GND plane, which does more harm than good. It seems like a tricky thing to be able to do well, if at all. I would love to hear more about this.


5) Need to add bulk capacitance should be added to the following: uln2003 5V to gnd, H-bridge FET's, Power Rails, I2C multiplexer

    To be honest, the ULN2003 I find is the most abstract IC out of everything that is on there. I did not think it needed one as it is just a Darlington transistor array, and it is not preforming any sort of real logic. I am not super familiar/sure about adding capacitors to the MOSFET's. I do have one that connects VCC the common point for each phase of the half-bridge. In terms of the power rails, I thought that adding the capacitors specified by the datasheet for each linear regulator was sufficient. For the MCP23017, I sort of had the same logic for the ULN2003. I opted not to add any capacitors there because I did not see it as needing any sort of noise suppression or a constant flow of current. Generally speaking, its main job is just to pull the interrupt lines low when a switch is flicked or turn on an LED. I could be incorrect on this, and I understand a decoupling or bypass capacitor is always a good idea, I just did not think it needed one these cases.

6) Just a thought also, use of an Arduino Mega may help simplify some things. The increased analog pins would remove the need for the i2c mux. Also, more flash and ram would be a nice help. Also with the Arduino Mega, it could be modified into a daughter board that plugs into the existing pin headers.

    Oh absolutely, I even have a knock-off Arduino MEGA available to me, and that's initially the direction the project started. I was even considering using a Raspberry Pi 3. Using the chip from the MEGA would save some space and render the I/O expander as redundant, however, I am learning more by using these cool things. 

I sincerely appreciate your time, and the effort you put into reviewing my design. I would love to go over it with you and discuss it greater detail.


[1]: https://www.digikey.ca/en/products/detail/cts-frequency-controls/MXO45HST-3C-16M000000/1801910

**Comment by kyrel8silva** [comment] 2024-11-13 23:45
0. H-bridge drivers are only rated for 8V min. This means the drivers will only work for ~0.5 tau of the capacitor bank time constants. 
I didn't see you mention this issue when reviewing your comment. Honestly I don't have much experience running a motor driver off of supercaps like this. I don't know how these FET drivers will behave at lower voltages. I do think a driver like this is required for minimizing switching losses/heat, and it allows you to use all N-FET's which is super nice. This may just be something that needs to be tested in the real world before any conclusions can be derived. 

1. Sorry for my ignorance. Very cool idea to implement the standalone Xtal oscillator! I haven't seen one used for the atmega chips but if they support it, it should be fine. The only limitation seems to be the requirement of high current drive. Some voltage stabilization may be required under loads for this oscillator to play nicely. But again, real world testing will tell you all you need to know. 

2. Snubber or TVS diodes are super helpful when dealing with voltage spikes. Coming from the automotive world, they are my bread and butter. It is honestly crazy how many issues we have that are solved by simply slapping diodes everywhere. I'm glad you can see the potential of them! There are some nuanced characteristics for TVS diodes that can make implementation a bit more difficult. I'm more than happy to help with the TVS choices here if you want to chat about them sometime. 
[https://www.ti.com/lit/an/slvae37/slvae37.pdf](url)

3. Trace widths are normally not an issue, until they are. You are right, for signals and serial data trace widths don't matter as much. There are a few scenarios in which the traces that are normally low current can face instances of higher current, causing voltage drops and weird logic errors when interacting in the digital realm. Trace widths become important when dealing with capacitors/inductors surge currents/voltages. 2oz copper is not usually needed. The larger surface area of wider traces can dissipate more heat. Relying on thicker copper to soak up the extra heat may just hide heat dissipation issues. Usually if I find I need 2oz copper, I start using parallel traces (top-bottom, or top-mid) and stitching them together with via's to increase the thermal conductivity and capacity. This is known as via stitching. 
[https://www.globalwellpcba.com/pcb-via-stitching/](url)

4. Ground plane stuff is definitely not intuitive. I agree with the general consensus that it usually is not needed. For large current applications like this, it usually is a good idea. The current traveling along the ground plane can cause a difference in the "ground" voltage measured at the h-bridge drivers vs the other components. This difference becomes much greater when dealing with surge currents and high frequency noise that can be induced when driving inductive loads with FET's. The addition of bulk capacitance can assist in reducing the surge current traveling long distances across the PCB. Switching to a 4-layer PCB and having dedicated internal power/ground planes can be super helpful in reducing EMI and limiting the requirement of isolating the analog-digital grounds. 

5.Bulk capacitance is a kind of safety catch to improve the stability of electronics during fast current switching. As the current draw of the electronics changes, the capacitor is able to stabilize the voltage seen by the device. Different capacitors can deliver current at different rates due to equivalent series resistance (ESR), plus a bunch of different stuff. Capacitors of different values (0.1uF, 1uF, 10uF, 100uF), also known as decades, are usually added in parallel in order to help filter different frequencies of noise. 
You are correct in thinking that some of the devices that you are using do not draw much current, so they shouldn't need large capacitors. The issue is that these devices can switch voltages very quickly, (like nanosecond timescale) so they end up pulling the voltage low for tiny amounts of time, causing brown-out conditions. 
The MCP23017 will also need to deal with the back EMF when the relay's coils are turned off. It looks like they should be able to handle it, but that initial voltage spike that occurs before the diode has completely turned on can be subdued with capacitors. Same goes for the FET outputs as well. 
[https://www.ti.com/lit/an/slvaft0/slvaft0.pdf?ts=1731516352190](url)

6. Fair point on the Mega, after all this is just a learning experience and you are definitely doing that! Damn you must have learnt so much doing all this. I hope I can help make it successful! There are a bunch of weird nuances involved when dealing with some of these systems so I hope I can help guide you through some of those scenarios. 

I feel like you have a good idea of where you want this project to go and I may be making some assumptions of your expected operation/implementation. I'm sure a quick call sometime would bring me up to speed on a bunch of things I am missing out on. I'll message you on discord to setup some review/catchup session.

**Comment by Fischer-Andrew** [comment] 2024-11-16 20:59
Hello [kyrel8silva](https://github.com/kyrel8silva), thank you for your detailed response. I apologize for not addressing the issue you pointed out about the MOSFET drivers, I will make sure to talk about it in this comment.

0. H-bridge drivers are only rated for 8V min. This means the drivers will only work for ~0.5 tau of the capacitor bank time constants.

    To my understanding, there I do not believe there is a real minimum VCC that is required to operate an IR2104. The IR2104 is a half-bridge bootstrap driver, where you only need logic level inputs on IN to operate it. The VCC applied charges the bootstrap capacitor while the low-side MOSFET conducts. I wrote an explanation of how an NMOSFET bootstrap circuit works, to reinforce my learning (I like to explain things) or even if you maybe did not know about it, or even for someone to correct me on a potential misunderstanding:
    
    EXPLANATION: It is important to note that the negative terminal of the bootstrap capacitor is connected to the source of the 'high-side' MOSFET. The instant when IN is logic HIGH, the positive side of the bootstrap capacitor is at a potential of ~VCC. As the MOSFET begins to turn on, VS approaches VD, and there is more voltage across the load. Without the bootstrap capacitor, the potential difference between the source and the gate, VGS decreases as the source voltage increases. However, since the negative side of the capacitor effectively 'captures' this difference, it leads to a voltage at the gate of VCC + VS. As a result, the gate-source voltage is ideally always VCC. 
   
    It makes sense that the minimum VCC is recommended to be 10V for the IR2104, as that's typically when most MOSFETs are 'fully on'. Since my bike is intended to operate at around a peak current of 15A, it means that for the IRFZ44N, an inspection of the typical output characteristics graph below tells me that I only need a VGS of 5.5V to still operate in the linear region.  
    
![image](https://github.com/user-attachments/assets/cc0e5cdb-4890-43f5-9053-fe024bd2c50a)

To end my rant about MOSFETs (sorry, I took this opportunity to say what I have learned so far haha), you still have an absolutely valid point. (TLDR:) I did completely fail to mention anywhere that I am using a secret 12V battery bank that plugs into the barrel jack on the PCB. This is to ensure all of the electronics/ICs are powered completely independently of the super-capacitors for safety, and efficiency. 

1. Standalone XTAL 

    No worries whatsoever, and thank you! I will talk more about voltage stabilization etc. in section 5.

2. Snubber or TVS diodes

    Very interesting! I have not had a ton of time to look into them, but I would love to hear more about what you know about them, their nuances and how to use them.
    
3. Trace widths
    
    I had no idea about the concept of trace stitching, thank you for the resource! I am curious to learn more about which traces on my PCB should be revised. 

4. Ground Plane
     
    I already have concepts of a second version of this PCB, which would be 4 layers (I have not even fully soldered in all of the parts of the PCBs that recently arrived haha). I’m still wrapping my head around the fact that different parts of the ground plane might not always be at the same potential.  It would be fascinating to empirically measure these variations, especially the surge currents and the noise from the switching components. I think observing this firsthand would really help to deepen my understanding.
        
5. Bulk Capacitance

    I am kind of curious about the need for these still, as I have all the electronics powered through linear regulators. Considering all of the high-voltage switching is occurring on the VCC plane, and the linear regulators are powered independently from the batteries, I don't see a need for decoupling capacitors to smooth out the current delivery. I should look into the time it takes for a linear regulator to correct the voltage after a transient, but to my current understanding, it seems implausible for a brownout condition to occur. 

    On second thought, the traces do go through the VCC plane, and it does make sense that the EMI from the high-speed switching can cause unanticipated behaviour. To be honest, when I was designing it, I did not account for noise coupling. The importance of it started to click after arguing why I thought that could not be a potential issue. Also, you are totally right about the ULN2003. I had a lapse of judgment and missed that the flyback diodes were transferring the voltage spike back to COM, where all the ICs are connected. 

    Thank you again for your time spent responding to my previous comment. You are well-spoken, and you made your points clear. I sincerely appreciate that. I hope my answers are well written, as I will not lie, I wrote these answers mostly in between (and sometimes during) classes. I am thrilled by the opportunity to have a live session and discuss my design and the issues more in detail, and I have reached out to you on Discord.
    
I will close this thread, and I will update the main README.md file on main with all the issues we discussed (and will further discuss), with you given full credit.

**Comment by Fischer-Andrew** [comment] 2024-11-19 01:43
To recap, I plan on making a subsequent version, after I have sufficiently tested my current design. All issues you have mentioned will be credited. Please stay tuned!

**Closed as completed by Fischer-Andrew** 2024-11-19 01:43 UTC
